name: Shell-Commands

on: [push]

jobs:
  linux-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello World"
      - name: multi line script
        run: |
          npm -v
          node --version
      - name: Python
        run: |
          import os
          print(os.getcwd())
        shell: python
