name: Shell-Commands

on: [push]

jobs:
  linux-shell:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multi line script
        run: |
          npm -v
          node --version
      - name: Python
        run: |
          import os
          print(os.getcwd())
        shell: python
  windows-shell:
    runs-on: windows-latest
    needs: [linux-shell]
    steps:
      - name: Powershell
        run: Get-Location
      - name: From Bash
        run: pwd
        shell: bash
